dist: xenial
language: node_js

node_js:
  - lts/*

before_install:
  - go get github.com/nats-io/nats-streaming-server
  - nohup nats-streaming-server > /dev/null 2>&1 &

install: npm i

script: nyc npm test && nyc report --reporter=text-lcov | coveralls
