dist: xenial
language: go

node_js:
  - lts/*

go:
  - "1.8"

before_install:
  - go get github.com/nats-io/nats-streaming-server
  - nohup nats-streaming-server > /dev/null 2>&1 &

install: npm i

script: nyc npm test && nyc report --reporter=text-lcov | coveralls
